// This file is automatically generated by qtc from "fasthttp_router.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line lib/templates/web/qtpl/fasthttp_router.qtpl:1
package qtpl

//line lib/templates/web/qtpl/fasthttp_router.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line lib/templates/web/qtpl/fasthttp_router.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line lib/templates/web/qtpl/fasthttp_router.qtpl:1
func StreamFastHTTPRouter(qw422016 *qt422016.Writer, packageName string) {
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:1
	if packageName == "main" {
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:1
		qw422016.N().S(`package main`)
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:1
	} else {
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:1
		qw422016.N().S(`package `)
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:1
		qw422016.E().S(packageName)
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:1
	}
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:1
	qw422016.N().S(`

import (`)
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:3
	if packageName == "main" {
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:3
		qw422016.N().S(`
	"flag"
`)
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:5
	}
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:5
	qw422016.N().S(`
	"github.com/kirillDanshin/dlog"
	"github.com/kirillDanshin/fap/web"
	"github.com/kirillDanshin/myutils"
)
`)
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:10
	if packageName == "main" {
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:10
		qw422016.N().S(`
var (
	address = flag.String("address", "127.0.0.1:3270", "address to bind")
)`)
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:13
	}
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:13
	qw422016.N().S(`

`)
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:15
	if packageName == "main" {
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:15
		qw422016.N().S(`func main() {
	flag.Parse()
	addr := *address
`)
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:18
	} else {
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:18
		qw422016.N().S(`func Run(addr string) {`)
		//line lib/templates/web/qtpl/fasthttp_router.qtpl:18
	}
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:18
	qw422016.N().S(`
	dlog.F("Registering handlers")

	w := web.New(addr)

	w.RegisterChain(getRouteChain())

	dlog.F("Listening on %s", addr)
	myutils.LogFatalError(w.ListenAndServeGZip())
}
`)
//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
}

//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
func WriteFastHTTPRouter(qq422016 qtio422016.Writer, packageName string) {
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
	StreamFastHTTPRouter(qw422016, packageName)
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
}

//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
func FastHTTPRouter(packageName string) string {
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
	WriteFastHTTPRouter(qb422016, packageName)
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
	qs422016 := string(qb422016.B)
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
	//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
	return qs422016
//line lib/templates/web/qtpl/fasthttp_router.qtpl:28
}
