// This file is automatically generated by qtc from "homeHandler.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line lib/templates/web/qtpl/homeHandler.qtpl:1
package qtpl

//line lib/templates/web/qtpl/homeHandler.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line lib/templates/web/qtpl/homeHandler.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line lib/templates/web/qtpl/homeHandler.qtpl:1
func StreamHomeHandler(qw422016 *qt422016.Writer, packageName string) {
	//line lib/templates/web/qtpl/homeHandler.qtpl:1
	if packageName == "main" {
		//line lib/templates/web/qtpl/homeHandler.qtpl:1
		qw422016.N().S(`package main`)
		//line lib/templates/web/qtpl/homeHandler.qtpl:1
	} else {
		//line lib/templates/web/qtpl/homeHandler.qtpl:1
		qw422016.N().S(`package `)
		//line lib/templates/web/qtpl/homeHandler.qtpl:1
		qw422016.E().S(packageName)
		//line lib/templates/web/qtpl/homeHandler.qtpl:1
	}
	//line lib/templates/web/qtpl/homeHandler.qtpl:1
	qw422016.N().S(`

import (
	"github.com/valyala/fasthttp"
)

var (
	homeGreetsTpl = []byte("Hi, ")
	homeGreetsNameParam = "name"
	homeGreetsDefaultName = []byte("Guest")
)

func homeHandler(ctx *fasthttp.RequestCtx) {
	ctx.Write(homeGreetsTpl)
	if name := ctx.UserValue(homeGreetsNameParam); name != nil && len(name.(string)) > 0 {
		ctx.WriteString(name.(string))
	} else {
		ctx.Write(homeGreetsDefaultName)
	}
}
`)
//line lib/templates/web/qtpl/homeHandler.qtpl:21
}

//line lib/templates/web/qtpl/homeHandler.qtpl:21
func WriteHomeHandler(qq422016 qtio422016.Writer, packageName string) {
	//line lib/templates/web/qtpl/homeHandler.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line lib/templates/web/qtpl/homeHandler.qtpl:21
	StreamHomeHandler(qw422016, packageName)
	//line lib/templates/web/qtpl/homeHandler.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line lib/templates/web/qtpl/homeHandler.qtpl:21
}

//line lib/templates/web/qtpl/homeHandler.qtpl:21
func HomeHandler(packageName string) string {
	//line lib/templates/web/qtpl/homeHandler.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line lib/templates/web/qtpl/homeHandler.qtpl:21
	WriteHomeHandler(qb422016, packageName)
	//line lib/templates/web/qtpl/homeHandler.qtpl:21
	qs422016 := string(qb422016.B)
	//line lib/templates/web/qtpl/homeHandler.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line lib/templates/web/qtpl/homeHandler.qtpl:21
	return qs422016
//line lib/templates/web/qtpl/homeHandler.qtpl:21
}
