// This file is automatically generated by qtc from "getRouteChain.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:1
package qtpl

//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:1
func StreamGetRouteChain(qw422016 *qt422016.Writer, packageName string) {
	//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:1
	if packageName == "main" {
		//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:1
		qw422016.N().S(`package main`)
		//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:1
	} else {
		//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:1
		qw422016.N().S(`package `)
		//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:1
		qw422016.E().S(packageName)
		//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:1
	}
	//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:1
	qw422016.N().S(`

import (
	"github.com/kirillDanshin/fap/web"
)

func getRouteChain() web.HandlersChain{
	return web.HandlersChain{
		web.MethodGET: web.MethodChain{
			"/": homeHandler,
			"/:name": homeHandler,
		},
	}
}

`)
//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
}

//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
func WriteGetRouteChain(qq422016 qtio422016.Writer, packageName string) {
	//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
	StreamGetRouteChain(qw422016, packageName)
	//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
}

//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
func GetRouteChain(packageName string) string {
	//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
	//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
	WriteGetRouteChain(qb422016, packageName)
	//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
	qs422016 := string(qb422016.B)
	//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
	//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
	return qs422016
//line lib/templates/webrdb/qtpl/getRouteChain.qtpl:16
}
